DELETE http://localhost:3001/api/recipes/RECIPEID
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InN1cGVydXNlckBlbWFpbC5jb20iLCJpZCI6IjY1MjQyNGZiYzc1YWIwNzVjYzYyZDE3YyIsImlhdCI6MTY5Njg2ODM3MX0.ReVNAwd922Ah5x523IYpFKlOMr_So2CMtHsDsca78Vw